pypi-pytest: Autospec creation for update from version 7.1.3 to version 7.2.0
Aaron Berdy (1):
      fix typo in pytester docs

Adam Turner (1):
      Use an explicit encoding when opening `os.devnul`

Albert Villanova del Moral (2):
      Fix typo in example/markers docs
      Fix cross-reference in reference/reference docs

Alice Purcell (2):
      Pass importmode to import_path in DoctestModule
      Added Alice Purcell to AUTHORS

Anthony Sottile (26):
      temporarily pin jinja2 version for docs build
      fix comparison of dataclasses with `InitVar`
      fix some typos to ensure pre-commit.ci fixes main
      update does_not_raise docs now that pytest is 3.7+ only
      git mv changelog/3396.{improvement,bugfix}.rst
      replace atomicwrites with os.replace
      vendor py.path and py.error
      use module __getattr__ for py.error to fix doctesting
      use getrawcode from _pytest._code
      remove other py.* accesses in _pytest._py.path
      _pytest._py.path: remove fspath compat
      _pytest._py.path: remove _cmp compat
      _pytest._py.path: remove decorator compat
      _pytest._py.error: mypy typing
      _pytest._py.path: importlib mode always available
      _pytest._py.path: flake8 fixes
      _pytest._py.path: combine Checkers classes
      _pytest._py.path: combine PosixPath into LocalPath
      _pytest._py.path: combine PathBase and LocalPath
      _pytest._py.path: get mypy passing
      add py.path.local tests
      fix test pollution of sys.modules
      adjust tests if py library is installed
      add -pylib tox environment
      add deprecation changelog for py library vendoring
      allow jobs to pass if codecov.io fails

Anton Yakutovich (1):
      Bump actions in test.yml

Babak Keyvani (2):
      improve `pytest.raises`
      improve `pytest.raises` - cont'd

Brandon Chinn (1):
      Fix partially unknown type (#10204)

Bruno Oliveira (19):
      Split test/deploy workflows
      Change directories during some tests in test_collection.py
      Prepare release version 7.1.2 (#9881)
      Add colors to summary (#9875)
      Add CHANGELOG for #9873 (#9953)
      Refer to py.path.local instead of LEGACY_PATH constant for better docs
      Do not advertise that importlib will be default import mode
      Mark pdb+expect tests as xfail for now
      Use PurePath directly instead of os.path.sep in rewrite.py
      Do not call tearDown for skipped unittest.TestCases with --pdb
      Update changelog/9877.bugfix.rst
      Fix mypy pre-commit run
      Add reference to the Where to patch docs in monkeypatch.setattr (#10217)
      Sort fixtures in reference.rst alphabetically
      Fix regendoc
      Merge pull request #10259 from pytest-dev/release-7.1.3
      Improve documentation for setup() and teardown() nose support
      Ignore mypy error about missing generic arg for catch_warnings
      Update to autoflake to 1.7.3

Chanvin Xiao (1):
      Doc: Clear mailbox before deleting the user

Cheuk Ting Ho (1):
      Warn when test functions return other than None (#9956)

Chris Wheeler (1):
      Add support for .pytest.ini as an alternative to pytest.ini

EmptyRabbit (1):
      Update changelog/9877.bugfix.rst

Ezio Melotti (1):
      Fix rst markup in TempdirFactory's docstring.

Florian Best (1):
      [style]: fix typo in docstring

Florian Bruhin (7):
      doc: Reformat/Modernize some code (#9900)
      Update training list
      Remove europython training (#10107)
      Update open trainings
      doc: Add link for enterPy training (#10299)
      Mark tryfirst/trylast as deprecated in their docs.
      doc: Add second day for enterPy training (#10348)

Fredrik Berndtsson (1):
      doc: Fix 404 'identify flaky test' link (#10244)

Gabriel Landau (4):
      Don't break into `pdb` for `raise unittest.SkipTest()`
      Test fix
      Changelog
      Add Gabriel Landau to AUTHORS

Gergely Kalmár (1):
      Ignore editable installation modules (#10231)

Hugo van Kemenade (4):
      Docs: link to easy issues in contributing guide
      Increase stacklevel to point at user's code (#9869)
      Document the --code-highlight default (#9883)
      Replace deprecated logging.warn with .warning

James Gerity (1):
      Indicate support for a tuple of exceptions in xfail raises=

John Litborn (1):
      fallback to native traceback when handling ExceptionGroup (take 2) [SQUASH] (#10209)

Jon Parise (3):
      Use safe_getattr() in getfixturemarker()
      Let mkdir() and mkpydir() receive PathLike names
      Add shell-style wildcard support to 'testpaths' (#9897)

Kevin C (1):
      Clarify writing_plugins naming instructions

Kian Eliasi (1):
      Remove unnecessary numpy import (#9798)

MatthewFlamm (1):
      Clarify precision when using NUMBER option in --doctest-modules (#9914)

Miro Hrončok (1):
      Adjust tests for a last minute Python 3.11 change in the traceback format

Nate Meyvis (2):
      Add note on tags to CONTRIBUTING.rst
      Fix typos in CONTRIBUTING.rst

Neil Girdhar (1):
      Use symbolic NoReturn as a type annotation (#10018)

Nhieuvu1802 (1):
      build(deps): Bump pytest-asyncio in /testing/plugins_integration (#10212)

Nipunn Koorapati (1):
      Add typing for FixtureRequest.param (#10133)

Ofek Lev (1):
      Fix packaging example

Paul Müller (5):
      fix: move 'import getpass' statement to try-clause
      Update AUTHORS
      Create 9871.bugfix.rst
      cleanup
      Update 9871.bugfix.rst

Paul Reece (2):
      Added Docstring description for the Path property of the FixtureRequest class.
      Added self to Authors

Pax (1):
      Add link to python docs on logging levels (#9925)

Pete Baughman (1):
      Improve error message in getfixturevalue

Peyman Salehi (1):
      Fix default encoding in cacheprovider

Philipp A (1):
      Revamp good practices (#10206)

Ran Benita (13):
      Merge pull request #9758 from pytest-dev/release-7.1.0
      testing: fix tests when run under `-v` or `-vv`
      config: restore pre-pytest 7.1.0 confcutdir exclusion behavior
      Merge pull request #9785 from pytest-dev/release-7.1.1
      testing: fix Path.rglob("") failures in Python 3.11b1
      doc: require sphinx 5
      doc: have tighter control on what autodoc shows
      doc: workaround for ugly API docs for overloaded functions with new Sphinx
      changelog: add missing entry for PR #9248
      mark: allow any Sequence[str] for parametrize(argnames), not just list/tuple
      pyproject.toml: remove `wheel` from `build-system.requires`
      ci: fix PR not triggering workflows by switching back to pytestbot access token
      Revert "ci: fix PR not triggering workflows by switching back to pytestbot access token"

Robert O'Shea (1):
      Added file-like methods to DontReadFromInput (#10173)

Ronny Pfannschmidt (15):
      Enhance errors for exception/warnings matching (#8508)
      deprecate hook configuration via marks/attributes
      remove the setup.py for the py.test project which for deprecation has been deployed since 2014
      handle non-true options in hookspec warning
      simplify typing for legacy hook mark support
      unify option extraction for legacy hook marks
      add docstring to warn_explicit_for
      bump plugin test pytest cov pin
      fix #10342: put location into warning exceptions
      Update src/_pytest/warning_types.py
      fix #7792: consider marks from the mro
      fixup: annotations
      fixup: mark mro test reformatt
      fixup: mark mro test reformatt
      Apply suggestions from code review

Rowin (1):
      Typo correction

Ruth Comer (1):
      doc: link to pytest-subtests

Samuel Colvin (1):
      Remove newlines from left/right operands with '-vv' (#9743)

Samuel Gaist (1):
      doc: add note to help modernize code bases to use pathlib

Sandro Tosi (1):
      Update location of `usage.rst` to fix manpage compilation

Shantanu (2):
      Use tomllib on Python 3.11 (#9741)
      Re-export importlib.metadata from _pytest.compat (#9906)

Simon K (1):
      Add deprecations for tests written for `nose` (#9907)

Stephen Rosen (1):
      Add monkeypatch.context() to how-to doc intro

Sviatoslav Sydorenko (2):
      Mention `monkeypatch.context()` in the docs (#10192)
      Drop `wheel` from `pyproject.toml` example

Tatiana Ovary (1):
      Update documentation on how pytest.warns affects DeprecationWarning #9291 (#10141)

Thierry Moisan (1):
      Fix a few broken links in the documentation

Thomas Grainger (2):
      Update :class:`pytest.PytestUnhandledCoroutineWarning` to a deprecation; it will raise an error in pytest 8. [SQUASH] (#10012)
      PytestReturnNotNoneWarning now subclasses PytestRemovedIn8Warning (#10196)

Tim Hoffmann (6):
      Consistently add **Tutorial**: in front of how-to links in reference
      Move documentation contents from reference.rst to docstrings
      Remove docs on Python 2.7 and 3.4 Support (#9957)
      Remove "Python 2.7 and 3.4 Support" from globaltoc
      Reorder the reference guides in the docs
      Declutter doc entry page (#9969)

Tobias Diez (6):
      Clarify error message in case no collectors are found for a file
      Fix rename issue
      Fix tests
      Fix more tests
      Add changelog
      Add to AUTHORS

Tony Narlock (6):
      docs(monkeypatch): Fix autodoc reference links (#10013)
      Export `pytest.DoctestItem` for typing / runtime purposes (#10313)
      :wrench: Negating --showlocals with --no-showlocals
      test(--no-showlocals): Should hide locals when addopts=--showlocals
      docs(output): Note --no-show-locals
      docs: Update changelog for --no-show-locals

Vivaan Verma (1):
      Replace entrypoint example with `pyproject.toml` in docs (#10359)

Wolfremium (1):
      Explicit note that tmpdir fixture is discouraged in favour of tmp_path #9937 (#10138)

Zac Hatfield-Dodds (5):
      Fix CI for Python 3.11
      Fix wrong `log_file` docs (#9878)
      type-ignore in error-message test
      Move changelog file
      Update 8646.improvement.rst

Zach OBrien (1):
      Fix representation of tuples in approx

aizpurua23a (1):
      Update fixtures.rst w/ finalizer order

dependabot[bot] (18):
      build(deps): Bump twisted in /testing/plugins_integration
      build(deps): Bump django in /testing/plugins_integration
      build(deps): Bump twisted in /testing/plugins_integration
      build(deps): Bump pytest-asyncio in /testing/plugins_integration (#9824)
      build(deps): Bump anyio[curio,trio] in /testing/plugins_integration
      build(deps): Bump django from 4.0.4 to 4.0.5 in /testing/plugins_integration (#10021)
      build(deps): Bump pytest-mock in /testing/plugins_integration
      build(deps): Bump django in /testing/plugins_integration
      build(deps): Bump pytest-mock in /testing/plugins_integration
      build(deps): Bump pytest-sugar in /testing/plugins_integration
      build(deps): Bump pytest-bdd in /testing/plugins_integration
      build(deps): Bump django in /testing/plugins_integration (#10195)
      build(deps): Bump django in /testing/plugins_integration
      build(deps): Bump twisted in /testing/plugins_integration
      build(deps): Bump pytest-mock in /testing/plugins_integration
      build(deps): Bump django in /testing/plugins_integration
      build(deps): Bump pytest-mock in /testing/plugins_integration
      build(deps): Bump pytest-twisted in /testing/plugins_integration

github-actions[bot] (8):
      [automated] Update plugin list (#9864)
      [automated] Update plugin list (#9959)
      [automated] Update plugin list (#9985)
      [automated] Update plugin list (#10001)
      [automated] Update plugin list (#10020)
      [automated] Update plugin list (#10194)
      [automated] Update plugin list (#10214)
      [automated] Update plugin list (#10253)

gresm (1):
      Update goodpractices.rst

holesch (1):
      JUnit XML: Escape error messages in setup/teardown (#10190)

itxasos23 (1):
      Handle NFC/NFD strings that normalize to the same string. (#10355)

johnkangw (1):
      Mention use of re_assert for strings in approx docs

pre-commit-ci[bot] (27):
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate (#9769)
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate (#9936)
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate (#10178)
      [pre-commit.ci] pre-commit autoupdate (#10256)
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks

pytest bot (18):
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      [automated] Update plugin list
      Prepare release version 7.2.0

skhomuti (1):
      Add allure-pytest to the popular plugins list

sommersoft (1):
      Do not truncate crash messages in short test summary on CI (#9933)

wodny (1):
      Mention pythonpath confval in Good Integration Practices (#10314)

zx.qiu (2):
      Fix stage caplog records not clear
      Use records.clear() in LogCaptureHandler when caplog.clear()